#!/usr/bin/env python

import sys, tempfile, random, re
from Bio import SeqIO, AlignIO, Seq, SeqRecord, Phylo
from Bio.Align import MultipleSeqAlignment
from Bio.SeqRecord import SeqRecord
import os, time
import collections
import StringIO
import csv
