#!/usr/bin/env python

import sys, tempfile, random, re
from Bio import SeqIO, AlignIO, Seq, SeqRecord, Phylo
from Bio.Align import MultipleSeqAlignment
from Bio.SeqRecord import SeqRecord
import os, time
import collections
import StringIO
import csv

em_A={}
em_B={}
em_C={}

with open("4A_empai.tsv", "rb") as read1:
	r1=csv.reader(read1, delimiter='\t')
	for line in r1:
		em_A[line[0]]=line[1]
with open("4B_empai.tsv", "rb") as read2:
	r2=csv.reader(read2, delimiter='\t')
	for line in r2:
		em_B[line[0]]=line[1]
with open("4C_empai.tsv", "rb") as read3:
	r3=csv.reader(read3, delimiter='\t')
	for line in r3:
		em_C[line[0]]=line[1]
avgEm={}		
sharedProt=set(em_A.keys()) & set(em_B.keys()) & set(em_C.keys())

#print sharedProt
avgEm=dict.fromkeys(sharedProt,0)
#print len(avgEm)
#print em_C.has_key('Protein')
#if (em_A.has_key('Protein'))== False:
#	print 'aaaaa'
#print em_1A.keys()

wEmpai=[]

for key in avgEm:
	avgEm[key]=(float(em_A[key])+float(em_B[key])+float(em_C[key]))/3
	#print avgEm[key]
	wEmpai.append([key,avgEm[key]])

#print wEmpai

with open ('4_empai.tsv', 'wb') as w:
	wr=csv.writer(w, delimiter='\t')
	wr.writerows(wEmpai)

read1.close()
read2.close()
read3.close()
w.close()
