#!/usr/bin/env python

import sys, tempfile, random, re
from Bio import SeqIO, AlignIO, Seq, SeqRecord, Phylo
from Bio.Align import MultipleSeqAlignment
from Bio.SeqRecord import SeqRecord
import os, time
import collections
import StringIO
import csv

observed=[]
observable={}

with open("3C_countObserved.tsv", "rb") as read:
	reader=csv.reader(read, delimiter='\t')
	for line in reader:
		observed.append(line)
with open("countObservablePeptides.txt", "rb") as handle:
	r=csv.reader(handle, delimiter='\t')
	for line in r:
		#print line
		observable[line[0]]=line[1]
		#observable.append(line)
		
empai=[]
emSum=0
j=0
#print observable
#print observable.index('sp|P53858|BNI4_YEAST')
for element in observed:
	if element[0]!='Protein':
		j=(10**(float(element[1])/float(observable[element[0]])))-1
		empai.append([element[0], j])
		emSum+=j
		
	
#for i, j  in enumerate(observable):
#print emSum
#494.86318518
#print empai[0]
for item in empai:
	item[1]= float(item[1])/emSum
	#print emSum
	#i+=1
#print empai[0]

with open ('3C_empai_norm.tsv', 'wb') as w:
	wr=csv.writer(w, delimiter='\t')
	wr.writerows(empai)
read.close()
handle.close()
w.close()
